// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexus.Infrastructure.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260904160701_AdjustEmpresaConector")]
    partial class AdjustEmpresaConector
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgAplicacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoApp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodigoApp")
                        .IsUnique();

                    b.ToTable("IntgAplicacion", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgAplicacionConector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<long>("AplicacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConectorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordErp")
                        .HasColumnType("text");

                    b.Property<string>("TokenBearer")
                        .HasColumnType("text");

                    b.Property<string>("UrlBasePersonalizada")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioErp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConectorId");

                    b.HasIndex("AplicacionId", "ConectorId")
                        .IsUnique();

                    b.ToTable("IntgAplicacionConector", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgAplicacionEmpresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AplicacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("AplicacionId", "EmpresaId")
                        .IsUnique();

                    b.ToTable("IntgAplicacionEmpresa", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgAplicacionIntegracion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AplicacionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("IntegracionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IntegracionId");

                    b.HasIndex("AplicacionId", "IntegracionId")
                        .IsUnique();

                    b.ToTable("IntgAplicacionIntegracion", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgConector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoProtocolo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlBase")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("IntgConectores", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgEmpresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreRazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TipoIdentificacion", "NumeroIdentificacion")
                        .IsUnique();

                    b.ToTable("IntgEmpresas", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgEmpresaConector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConectorId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("ConectorId");

                    b.HasIndex("EmpresaId")
                        .IsUnique();

                    b.ToTable("IntgEmpresaConector", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgEmpresaIntegracionConector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("IntegracionConectorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("RequiereAutenticacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TokenBearer")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IntegracionConectorId");

                    b.HasIndex("EmpresaId", "IntegracionConectorId")
                        .IsUnique();

                    b.ToTable("IntgEmpresaIntegracionConectores", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgIntegracion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoAccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("ConsultaGenerica")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAccion")
                        .IsUnique();

                    b.ToTable("IntgIntegraciones", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgIntegracionConector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ColaRabbitMQDestino")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ConectorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("IntegracionId")
                        .HasColumnType("bigint");

                    b.Property<string>("RutaEndpoint")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConectorId");

                    b.HasIndex("IntegracionId", "ConectorId")
                        .IsUnique();

                    b.ToTable("IntgIntegracionConectores", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.UnoEConsultaConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoConsulta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("IdProveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreConexion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlantillaParametrosXml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodigoConsulta")
                        .IsUnique();

                    b.ToTable("UnoEConsultaConfig", "public");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("User");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgAplicacionConector", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Integraciones.IntgAplicacion", "Aplicacion")
                        .WithMany("AplicacionConectores")
                        .HasForeignKey("AplicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexus.Domain.Entities.Integraciones.IntgConector", "Conector")
                        .WithMany("AplicacionConectores")
                        .HasForeignKey("ConectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aplicacion");

                    b.Navigation("Conector");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgAplicacionEmpresa", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Integraciones.IntgAplicacion", "Aplicacion")
                        .WithMany("AplicacionEmpresas")
                        .HasForeignKey("AplicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexus.Domain.Entities.Integraciones.IntgEmpresa", "Empresa")
                        .WithMany("AplicacionEmpresas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aplicacion");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgAplicacionIntegracion", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Integraciones.IntgAplicacion", "Aplicacion")
                        .WithMany("AplicacionIntegraciones")
                        .HasForeignKey("AplicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexus.Domain.Entities.Integraciones.IntgIntegracion", "Integracion")
                        .WithMany("AplicacionIntegraciones")
                        .HasForeignKey("IntegracionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aplicacion");

                    b.Navigation("Integracion");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgEmpresaConector", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Integraciones.IntgConector", "Conector")
                        .WithMany("EmpresaConectores")
                        .HasForeignKey("ConectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexus.Domain.Entities.Integraciones.IntgEmpresa", "Empresa")
                        .WithOne("EmpresaConector")
                        .HasForeignKey("Nexus.Domain.Entities.Integraciones.IntgEmpresaConector", "EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conector");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgEmpresaIntegracionConector", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Integraciones.IntgEmpresa", "Empresa")
                        .WithMany("EmpresaIntegracionConectores")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexus.Domain.Entities.Integraciones.IntgIntegracionConector", "IntegracionConector")
                        .WithMany("EmpresaIntegracionConectores")
                        .HasForeignKey("IntegracionConectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("IntegracionConector");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgIntegracionConector", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Integraciones.IntgConector", "Conector")
                        .WithMany("IntegracionConectores")
                        .HasForeignKey("ConectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexus.Domain.Entities.Integraciones.IntgIntegracion", "Integracion")
                        .WithMany("IntegracionConectores")
                        .HasForeignKey("IntegracionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conector");

                    b.Navigation("Integracion");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgAplicacion", b =>
                {
                    b.Navigation("AplicacionConectores");

                    b.Navigation("AplicacionEmpresas");

                    b.Navigation("AplicacionIntegraciones");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgConector", b =>
                {
                    b.Navigation("AplicacionConectores");

                    b.Navigation("EmpresaConectores");

                    b.Navigation("IntegracionConectores");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgEmpresa", b =>
                {
                    b.Navigation("AplicacionEmpresas");

                    b.Navigation("EmpresaConector");

                    b.Navigation("EmpresaIntegracionConectores");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgIntegracion", b =>
                {
                    b.Navigation("AplicacionIntegraciones");

                    b.Navigation("IntegracionConectores");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integraciones.IntgIntegracionConector", b =>
                {
                    b.Navigation("EmpresaIntegracionConectores");
                });
#pragma warning restore 612, 618
        }
    }
}
